name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16, 18]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update APT
        run: sudo apt update

      - name: Install OS dependencies
        run: sudo apt install lcov

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: npm install

      - name: Lint
        run: npx grunt lint

      - name: Coverage
        run: npx grunt coverage --simulate

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage/lcov_final.info
